name: Build and publish

on:
  workflow_dispatch:
  push:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
        architecture: x64

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build and test
      run: ./gradlew check build

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          ./decoder/build/libs/java-midi-decoder-*.jar
          ./app/build/libs/app.jar
